# Generated by Django 3.2.3 on 2021-07-14 13:14

from django.db import migrations, models
import django.db.models.deletion
import picklefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_data', picklefield.fields.PickledObjectField(editable=False)),
                ('uploader_session', models.CharField(default='Not recorded', max_length=50)),
                ('uploader_email', models.CharField(default='Not logged in', max_length=150)),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_session', models.CharField(default='Not recorded', max_length=50)),
                ('notes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('ods_code', models.CharField(max_length=3, primary_key=True, serialize=False, unique=True)),
                ('organisation_name', models.CharField(default='', max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_session', models.CharField(default='Not recorded', max_length=50)),
                ('shift_type_name', models.CharField(max_length=150)),
                ('shift_start_time', models.TimeField()),
                ('shift_end_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ShiftBreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('break_start', models.TimeField()),
                ('break_end', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('ods_site_code', models.CharField(default='', max_length=4, primary_key=True, serialize=False, unique=True)),
                ('ods_code', models.ForeignKey(default='Unknown', on_delete=django.db.models.deletion.SET_DEFAULT, to='api.organisation')),
            ],
        ),
    ]
