# Generated by Django 3.2.1 on 2021-05-25 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('ods_code', models.CharField(default='', max_length=3, primary_key=True, serialize=False, unique=True)),
                ('organisation_name', models.CharField(default='', max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('ods_site_code', models.CharField(default='', max_length=4, primary_key=True, serialize=False, unique=True)),
                ('ods_code', models.ForeignKey(default='Unknown', on_delete=django.db.models.deletion.SET_DEFAULT, to='api.organisation')),
            ],
        ),
    ]
