# Generated by Django 3.2.3 on 2021-07-14 13:46

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicdata',
            name='uploaded_data',
            field=picklefield.fields.PickledObjectField(blank=True, editable=False, null=True),
        ),
    ]
