# Generated by Django 3.2.3 on 2021-07-15 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProphetForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_session', models.CharField(default='Not recorded', max_length=50)),
                ('stream', models.CharField(default='Not recorded', max_length=150)),
                ('prophet_forecast_df_feather', models.FileField(upload_to='forecasts')),
            ],
        ),
        migrations.CreateModel(
            name='ProphetModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_session', models.CharField(default='Not recorded', max_length=50)),
                ('stream', models.CharField(default='Not recorded', max_length=150)),
                ('prophet_model_json', models.JSONField()),
            ],
        ),
    ]
