# Generated by Django 3.2.3 on 2021-07-23 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_notes_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicdata',
            name='processing_complete_at',
            field=models.DateTimeField(null=True),
        ),
    ]
