# Generated by Django 3.2.1 on 2021-06-01 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210528_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicdata',
            name='uploader',
            field=models.CharField(default='Not recorded', max_length=50),
        ),
    ]
