# Generated by Django 3.2.3 on 2021-07-23 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_historicdata_processing_complete_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicdata',
            name='processing_complete_at',
        ),
        migrations.AddField(
            model_name='prophetforecast',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='prophetmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
