# Generated by Django 3.2.1 on 2021-06-01 12:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_historicdata_uploader'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicdata',
            name='upload_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
