# Generated by Django 3.2.3 on 2021-07-16 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_prophetforecast_prophet_forecast_df_feather'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShiftBreak',
        ),
        migrations.AddField(
            model_name='shift',
            name='break_1_end',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='shift',
            name='break_1_start',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='shift',
            name='break_2_end',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='shift',
            name='break_2_start',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='shift',
            name='break_3_end',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='shift',
            name='break_3_start',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='shift',
            name='shift_end_time',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='shift',
            name='shift_start_time',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='shift',
            name='shift_type_name',
            field=models.CharField(default='', max_length=150),
        ),
    ]
