# Generated by Django 3.2.3 on 2021-06-11 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_historicdata_upload_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicdata',
            old_name='uploader',
            new_name='uploader_session',
        ),
        migrations.AddField(
            model_name='historicdata',
            name='uploader_email',
            field=models.CharField(default='Not logged in', max_length=150),
        ),
    ]
