# Generated by Django 3.2.3 on 2021-07-23 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210723_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicdata',
            name='processing_initialised_at',
            field=models.DateTimeField(null=True),
        ),
    ]
