# Generated by Django 3.2.3 on 2021-07-18 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210716_1339'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_session', models.CharField(default='Not recorded', max_length=50)),
                ('role_name', models.CharField(default='', max_length=150)),
                ('decisions_per_hour_per_stream', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_session', models.CharField(default='Not recorded', max_length=50)),
                ('stream_name', models.CharField(default='', max_length=150)),
                ('stream_priority', models.IntegerField(default=1)),
                ('time_for_decision', models.IntegerField(default=30)),
            ],
        ),
    ]
