# Generated by Django 3.2.3 on 2021-07-18 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_role_stream'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicdata',
            name='processing_complete',
            field=models.BooleanField(default=False),
        ),
    ]
