# Generated by Django 3.2.3 on 2021-06-22 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210611_1428'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_session', models.CharField(default='Not recorded', max_length=50)),
                ('shift_type_name', models.CharField(max_length=150)),
                ('shift_start_time', models.TimeField()),
                ('shift_end_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ShiftBreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('break_start', models.TimeField()),
                ('break_end', models.TimeField()),
            ],
        ),
    ]
