# Generated by Django 3.2.3 on 2021-07-26 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rotaentry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rotaentry',
            name='week_end',
        ),
        migrations.RemoveField(
            model_name='rotaentry',
            name='week_start',
        ),
    ]
