# Generated by Django 3.2.3 on 2021-07-26 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210726_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rotaentry',
            name='resource_type',
            field=models.CharField(choices=[('core', 'Core'), ('ad hoc', 'Ad hoc')], default='core', max_length=10),
        ),
    ]
