# Generated by Django 3.2.3 on 2021-07-26 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_rotaentry_resource_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='rotaentry',
            name='prev_week',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prev_week', to='api.shift'),
        ),
    ]
