# Generated by Django 3.2.3 on 2021-07-27 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_additionalfactorcapacity_additionalfactordemand'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalFactorAvailableCapacity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_session', models.CharField(default='Not recorded', max_length=50)),
                ('factor_description', models.CharField(max_length=200)),
                ('all_streams', models.BooleanField()),
                ('percentage_change', models.FloatField()),
                ('increase_or_decrease', models.CharField(max_length=10)),
                ('stream', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.stream')),
            ],
        ),
        migrations.CreateModel(
            name='AdditionalFactorRequiredCapacity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_session', models.CharField(default='Not recorded', max_length=50)),
                ('factor_name', models.CharField(max_length=200)),
                ('percentage_change', models.FloatField()),
                ('increase_or_decrease', models.CharField(max_length=10)),
                ('all_streams', models.BooleanField()),
                ('factor_type', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_date', models.DateField()),
                ('end_time', models.TimeField()),
                ('stream', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.stream')),
            ],
        ),
        migrations.DeleteModel(
            name='AdditionalFactorCapacity',
        ),
        migrations.DeleteModel(
            name='AdditionalFactorDemand',
        ),
    ]
