# Generated by Django 3.2.3 on 2021-07-27 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_scenario'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='user_session',
            field=models.CharField(default='Not recorded', max_length=50),
        ),
    ]
