# Generated by Django 3.2.3 on 2021-07-27 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_scenario_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenario',
            name='start_date',
            field=models.CharField(default='', max_length=50),
        ),
    ]
