# Generated by Django 3.2.3 on 2021-07-27 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20210727_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalfactorrequiredcapacity',
            name='end_date',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='additionalfactorrequiredcapacity',
            name='start_date',
            field=models.CharField(default='', max_length=50),
        ),
    ]
